apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-api-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: api.myapp.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-api-svc
                port:
                  number: 80