
services:
  web-api-test-svc: ## for demonstration
    build: ./web-api-test/
    image: localhost:32000/web-api-test:latest
    ports:
      - 8000:80
    volumes:
      - ./web-api-test/:/var/www/html/
  database-svc:
    build: ./database
    image: loalhost:32000/database:latest
    ports: 
      - "5432:5432"
  
